server:
  port: 8080

spring:
  jackson:
    ## 默认序列化时区
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enterprise?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 1647022985
  data:
    redis:
      database: 6
      host: localhost
      port: 6379
      password: xiaoyu-redis
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  mail:
    username: 1647022985@qq.com
    protocol: smtp
    port: 587
    host: smtp.qq.com
    password: mpw:jvtyH9paRj/JMVYqyxDSwDq4pMxeBxbi5lHMm1AW8oU=
    ttl: 120
  cache:
    type: redis
    redis:
      key-prefix: Enterprise_ #key前缀
      use-key-prefix: true #是否开启key前缀
      cache-null-values: true #是否缓存空值


mybatis-plus:
  global-config:
    db-config:
      # 主键ID类型
      id-type: auto
      # 逻辑删除字段名称
      logic-delete-field: deleted
      # 逻辑删除-删除值
      logic-delete-value: 1
      # 逻辑删除-未删除值
      logic-not-delete-value: 0
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 认证配置
jwt:
  # 签署密钥
  secret-key: mpw:wI0xYvFTUidwig6+imZI/KcKhi+hROBeSWtJ/XHgvT3V+ru48vYgMDA8XrVIWSaa
  # token 过期时间(单位:秒)
  expiration: 18000

oss:
  # OSS 类型 (目前支持aliyun、minio)
  type: aliyun
  aliyun:
    # 服务Endpoint
    endpoint: mpw:/8Dn3bGSHD5KH/6jGby7hqKEWR4BG1MFBbjzQJDY5MM=
    # 访问凭据
    access-key-id: mpw:3b9zN3WwTA2ZatodAcJx/YM1Gr874p/B4Mr48mTF2eI=
    # 凭据密钥
    access-key-secret: mpw:CCOpiWSjXjjbdtBlvKuD92xOoWtS7fQou7GAgN3+HTY=
    # 存储桶名称
    bucket-name: mpw:14ec7NKEGZwJr5H/srNeWe9WUYWP1MCHhcHp0b+obC0=

# springdoc配置： https://springdoc.org/properties.html
springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    tags-sorter: alpha
  api-docs:
    enabled: true

# xxl-job 定时任务配置
xxl:
  job:
    admin:
      # 多个地址使用,分割
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: xxl-job-executor-${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30


captcha:
  #  验证码缓存过期时间(单位:秒)
  ttl: 120
  # 验证码内容长度
  length: 4
  # 验证码宽度
  width: 120
  # 验证码高度
  height: 40


# 系统配置
system:
  config:
    # 数据权限开关
    data-permission-enabled: true
    # 定时任务 xxl-job 开关
    xxl-job-enabled: false
    # WebSocket 开关
    websocket-enabled: true